version: "3"

services:
  spiderfoot:
    build:
       context: ./
    image: spiderfoot
    container_name: spiderfoot
    ports:
      - "5001:5001"
    environment:
      - SF_USERNAME=admin
      - SF_PASSWORD=admin
    restart: unless-stopped
